# Generated by Django 3.1.1 on 2020-10-12 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publisher_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('pub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publisher_list.publisher')),
            ],
        ),
    ]
