# Generated by Django 3.1.1 on 2020-10-12 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher_list', '0002_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pub_id',
            new_name='pub',
        ),
    ]
